#ifndef WINDER_PINS_H
#define WINDER_PINS_H

#define SETBIT(b, bi, v) b = (b & (0xff & ~(1 << bi))) | ((v & 1) << bi)

#define MAINBOARD_UNOCNC_SHIELD
//#define MAINBOARD_RAMPS_1_4

#if defined(MAINBOARD_UNOCNC_SHIELD)

#define UNOCNC_X_STEP_PIN	2
#define UNOCNC_X_DIR_PIN	5
#define UNOCNC_X_ENA_PIN	8

#define UNOCNC_Y_STEP_PIN	3
#define UNOCNC_Y_DIR_PIN	6
#define UNOCNC_Y_ENA_PIN	8

#define UNOCNC_Z_STEP_PIN	4
#define UNOCNC_Z_DIR_PIN	7
#define UNOCNC_Z_ENA_PIN	8

#define UNOCNC_X_ENDSTOP	9
#define UNOCNC_Y_ENDSTOP	10
#define UNOCNC_Z_ENDSTOP	11

//A0-14-PC0
#define	UNOCNC_ABORT	14

//A1-15-PC1
#define UNOCNC_HOLD		15

//A2-16-PC2
#define UNOCNC_RESUME	16


#define UNOCNC_SPINDLE_ENABLE	12
#define UNOCNC_SPINDLE_ENABLE_PORT	PORTB	
#define UNOCNC_SPINDLE_ENABLE_PINR	PINB	
#define UNOCNC_SPINDLE_ENABLE_BITN	4

#define UNOCNC_SPINDLE_DIR		13
#define UNOCNC_SPINDLE_DIR_PORT	PORTB
#define UNOCNC_SPINDLE_DIR_PINR	PINB
#define UNOCNC_SPINDLE_DIR_BITN	5

#define PIN_A0_DIGI		14
#define PIN_A1_DIGI		15
#define PIN_A2_DIGI		16
#define PIN_A3_DIGI		17
#define PIN_A4_DIGI		18
#define PIN_A5_DIGI		19

// CoolEn on A3
#define UNOCNC_COOL_ENABLE		PIN_A3_DIGI 		
#define UNOCNC_COOL_ENABLE_PORT		PORTC		
#define UNOCNC_COOL_ENABLE_PINR		PINC		
#define UNOCNC_COOL_ENABLE_BITN		3


#define PIN_X_STEP	UNOCNC_X_STEP_PIN
#define PIN_X_DIR	UNOCNC_X_DIR_PIN
#define PIN_X_ENA	UNOCNC_X_ENA_PIN

#define PIN_Y_STEP	UNOCNC_Z_STEP_PIN
#define PIN_Y_DIR	UNOCNC_Z_DIR_PIN
#define PIN_Y_ENA	UNOCNC_Z_ENA_PIN

#define PIN_Z_STEP	UNOCNC_Y_STEP_PIN
#define PIN_Z_DIR	UNOCNC_Y_DIR_PIN
#define PIN_Z_ENA	UNOCNC_Y_ENA_PIN

#define PIN_X_ENDSTOP	UNOCNC_X_ENDSTOP
#define PIN_Y_ENDSTOP	UNOCNC_Y_ENDSTOP
#define PIN_Z_ENDSTOP	UNOCNC_X_ENDSTOP


#define SET_X_STEP(v) 	SETBIT(PORTD, 2, v)
#define SET_X_DIR(v)	SETBIT(PORTD, 5, v)
#define SET_Y_STEP(v)	SETBIT(PORTD, 3, v)
#define SET_Y_DIR(v)	SETBIT(PORTD, 6, v)
#define SET_Z_STEP(v)	SETBIT(PORTD, 4, v)
#define SET_Z_DIR(v)	SETBIT(PORTD, 7, v)

#define SET_X_UNOCNC_STEP_ON 	PORTD |= 0x4
#define SET_X_UNOCNC_DIR_ON		PORTD |= 0x20 
#define SET_Y_UNOCNC_STEP_ON	PORTD |= 0x8
#define SET_Y_UNOCNC_DIR_ON		PORTD |= 0x40
#define SET_Z_UNOCNC_STEP_ON	PORTD |= 0x10
#define SET_Z_UNOCNC_DIR_ON		PORTD |= 0x80

#define SET_X_UNOCNC_STEP_OFF 	PORTD &= ~0x4
#define SET_X_UNOCNC_DIR_OFF	PORTD &= ~0x20 
#define SET_Y_UNOCNC_STEP_OFF	PORTD &= ~0x8
#define SET_Y_UNOCNC_DIR_OFF	PORTD &= ~0x40
#define SET_Z_UNOCNC_STEP_OFF	PORTD &= ~0x10
#define SET_Z_UNOCNC_DIR_OFF	PORTD &= ~0x80

#define SET_X_STEP_ON 		SET_X_UNOCNC_STEP_ON
#define SET_X_DIR_ON		SET_X_UNOCNC_DIR_ON
#define SET_Y_STEP_ON		SET_Z_UNOCNC_STEP_ON
#define SET_Y_DIR_ON		SET_Z_UNOCNC_DIR_ON
#define SET_Z_STEP_ON		SET_Y_UNOCNC_STEP_ON
#define SET_Z_DIR_ON		SET_Y_UNOCNC_DIR_ON

#define SET_X_STEP_OFF 		SET_X_UNOCNC_STEP_OFF
#define SET_X_DIR_OFF		SET_X_UNOCNC_DIR_OFF
#define SET_Y_STEP_OFF		SET_Z_UNOCNC_STEP_OFF
#define SET_Y_DIR_OFF		SET_Z_UNOCNC_DIR_OFF
#define SET_Z_STEP_OFF		SET_Y_UNOCNC_STEP_OFF
#define SET_Z_DIR_OFF		SET_Y_UNOCNC_DIR_OFF

// Muve
#define PIN_ROTARY_A_CLK	UNOCNC_COOL_ENABLE
#define PIN_ROTARY_A_CLK_PORT	UNOCNC_COOL_ENABLE_PORT
#define PIN_ROTARY_A_CLK_PINR	UNOCNC_COOL_ENABLE_PINR
#define PIN_ROTARY_A_CLK_BITN	UNOCNC_COOL_ENABLE_BITN
#define READ_ROTARY_A_CLK	((PIN_ROTARY_A_CLK_PINR & (1 << PIN_ROTARY_A_CLK_BITN)) ? 1 : 0)

// Gray
#define PIN_ROTARY_B_DT		UNOCNC_SPINDLE_DIR
#define PIN_ROTARY_B_DT_PORT		UNOCNC_SPINDLE_DIR_PORT
#define PIN_ROTARY_B_DT_PINR		UNOCNC_SPINDLE_DIR_PINR
#define PIN_ROTARY_B_DT_BITN		UNOCNC_SPINDLE_DIR_BITN
#define READ_ROTARY_B_DT	((PIN_ROTARY_B_DT_PINR & (1 << PIN_ROTARY_B_DT_BITN)) ? 1 : 0)

// WHITE
#define PIN_ROTARY_SW		UNOCNC_SPINDLE_ENABLE
#define PIN_ROTARY_SW_PORT		UNOCNC_SPINDLE_ENABLE_PORT
#define PIN_ROTARY_SW_PINR		UNOCNC_SPINDLE_ENABLE_PINR
#define PIN_ROTARY_SW_BITN		UNOCNC_SPINDLE_ENABLE_BITN
#define READ_ROTARY_SW	(int)((PIN_ROTARY_SW_PINR & (1 << PIN_ROTARY_SW_BITN)) ? 1 : 0)

#define WINDER_LS_STOP_1  UNOCNC_HOLD
#define WINDER_LS_STOP_2  UNOCNC_X_ENDSTOP

#define WINDER_LS_RUN_1  UNOCNC_Y_ENDSTOP
#define WINDER_LS_RUN_2  UNOCNC_Z_ENDSTOP

#endif

#if defined(MAINBOARD_RAMPS_1_4)

#define BITVAL_0	1
#define BITVAL_0_C	0xFE
#define BITVAL_1	2
#define BITVAL_1_C	0xFD
#define BITVAL_2	4
#define BITVAL_2_C	0xFB
#define BITVAL_3	8
#define BITVAL_3_C	0xF7
#define BITVAL_4	10
#define BITVAL_4_C	0xEF
#define BITVAL_5	20
#define BITVAL_5_C	0xDF
#define BITVAL_6	40
#define BITVAL_6_C	0xBF
#define BITVAL_7	80
#define BITVAL_7_C	0x7F

#define RAMPS_X_MIN_PIN	          	3
#define RAMPS_X_MIN_PORT           	PORTE
#define RAMPS_X_MIN_PINR           	PINE
#define RAMPS_X_MIN_BITVAL          BITVAL_5
#define RAMPS_X_MIN_BITVALC         BITVAL_5_C
#define RAMPS_X_MIN_BITN           	5

#define RAMPS_X_MAX_PIN			  	2
#define RAMPS_X_MAX_PORT           	PORTE
#define RAMPS_X_MAX_PINR           	PINE
#define RAMPS_X_MAX_BITVAL          BITVAL_4
#define RAMPS_X_MAX_BITVALC         BITVAL_4_C
#define RAMPS_X_MAX_BITN           	4

#define RAMPS_Z_MIN_PIN          18
#define RAMPS_Z_MAX_PIN          19
#define RAMPS_Y_MIN_PIN          14
#define RAMPS_Y_MAX_PIN          15


#define RAMPS_TEMP_0_PIN         A13   // Analog Input
#define RAMPS_TEMP_1_PIN         A15   // Analog Input
#define RAMPS_TEMP_BED_PIN       A14   // Analog Input

//D54-A0-PF0
#define RAMPS_X_STEP_PIN         54
#define RAMPS_X_STEP_PORT        PORTF
#define RAMPS_X_STEP_PINR        PINF
#define RAMPS_X_STEP_BITVAL      BITVAL_0
#define RAMPS_X_STEP_BITVALC     BITVAL_0_C
#define RAMPS_X_STEP_BITN        0

//D55-A1-PF1
#define RAMPS_X_DIR_PIN          55
#define RAMPS_X_DIR_POR          PORTF
#define RAMPS_X_DIR_PINR         PINF
#define RAMPS_X_DIR_BITVAL       BITVAL_1
#define RAMPS_X_DIR_BITVALC      BITVAL_1_C
#define RAMPS_X_DIR_BITN         1

//D38-PD7
#define RAMPS_X_ENABLE_PIN       38
#define RAMPS_X_ENABLE_PORT      PORTD
#define RAMPS_X_ENABLE_PINR      PIND
#define RAMPS_X_ENABLE_BITVAL    BITVAL_7
#define RAMPS_X_ENABLE_BITVALC   BITVAL_7_C
#define RAMPS_X_ENABLE_BITN      7

//D60-A6-PF6
#define RAMPS_Y_STEP_PIN         60
#define RAMPS_Y_STEP_PORT        PORTF
#define RAMPS_Y_STEP_PINR        PINF
#define RAMPS_Y_STEP_BITVAL      BITVAL_6
#define RAMPS_Y_STEP_BITVALC     BITVAL_6_C
#define RAMPS_Y_STEP_BITN        6

//D61-A7-PF7
#define RAMPS_Y_DIR_PIN          61
#define RAMPS_Y_DIR_PORT         PORTF
#define RAMPS_Y_DIR_PINR         PINF
#define RAMPS_Y_DIR_BITVAL       BITVAL_7
#define RAMPS_Y_DIR_BITVALC      BITVAL_7_C
#define RAMPS_Y_DIR_BITN         7

//D56-A2-PF2
#define RAMPS_Y_ENABLE_PIN       56
#define RAMPS_Y_ENABLE_PORT      PORTF
#define RAMPS_Y_ENABLE_PINR      PINF
#define RAMPS_Y_ENABLE_BITVAL    BITVAL_2
#define RAMPS_Y_ENABLE_BITVALC   BITVAL_2_C
#define RAMPS_Y_ENABLE_BITN      2

//D46-PL3
#define RAMPS_Z_STEP_PIN         46
#define RAMPS_Z_STEP_PORT        PORTL
#define RAMPS_Z_STEP_PINR        PINL
#define RAMPS_Z_STEP_BITVAL      BITVAL_3
#define RAMPS_Z_STEP_BITVALC     BITVAL_3_C
#define RAMPS_Z_STEP_BITN        3

//D48-PL1
#define RAMPS_Z_DIR_PIN          48
#define RAMPS_Z_DIR_PORT         PORTL
#define RAMPS_Z_DIR_PINR         PINL
#define RAMPS_Z_DIR_BITVAL       BITVAL_1
#define RAMPS_Z_DIR_BITVALC      BITVAL_1_C
#define RAMPS_Z_DIR_BITN         1

//D62-A8-PK0
#define RAMPS_Z_ENABLE_PIN       62
#define RAMPS_Z_ENABLE_PORT      PORTK
#define RAMPS_Z_ENABLE_PINR      PINK
#define RAMPS_Z_ENABLE_BITVAL    BITVAL_0
#define RAMPS_Z_ENABLE_BITVALC   BITVAL_0_C
#define RAMPS_Z_ENABLE_BITN      0

//D26-PA4
#define RAMPS_E0_STEP_PIN        26
#define RAMPS_E0_STEP_PORT       PORTA
#define RAMPS_E0_STEP_PINR       PINA
#define RAMPS_E0_STEP_BITVAL     BITVAL_4
#define RAMPS_E0_STEP_BITVALC    BITVAL_4_C
#define RAMPS_E0_STEP_BITN       4

//D28-PA6
#define RAMPS_E0_DIR_PIN         28
#define RAMPS_E0_DIR_PORT        PORTA
#define RAMPS_E0_DIR_PINR        PINA
#define RAMPS_E0_DIR_BITVAL      BITVAL_6
#define RAMPS_E0_DIR_BITVALC     BITVAL_6_C
#define RAMPS_E0_DIR_BITN        6

//D24-PA2
#define RAMPS_E0_ENABLE_PIN      24
#define RAMPS_E0_ENABLE_PORT     PORTA
#define RAMPS_E0_ENABLE_PINR     PINA
#define RAMPS_E0_ENABLE_BITVAL   BITVAL_2
#define RAMPS_E0_ENABLE_BITVALC  BITVAL_2_C
#define RAMPS_E0_ENABLE_BITN     2

//D36-PC1
#define RAMPS_E1_STEP_PIN        36
#define RAMPS_E1_STEP_PORT       PORTC
#define RAMPS_E1_STEP_PINR       PINC
#define RAMPS_E1_STEP_BITVAL     BITVAL_1
#define RAMPS_E1_STEP_BITVALC    BITVAL_1_C
#define RAMPS_E1_STEP_BITN       1

//D34-PC3
#define RAMPS_E1_DIR_PIN         34
#define RAMPS_E1_DIR_PORT        PORTC
#define RAMPS_E1_DIR_PINR        PINC
#define RAMPS_E1_DIR_BITVAL      BITVAL_3
#define RAMPS_E1_DIR_BITVALC     BITVAL_3_C
#define RAMPS_E1_DIR_BITN        3

//D30-PC7
#define RAMPS_E1_ENABLE_PIN      30
#define RAMPS_E1_ENABLE_PORT     PORTC
#define RAMPS_E1_ENABLE_PINR     PINC
#define RAMPS_E1_ENABLE_BITVAL   BITVAL_7
#define RAMPS_E1_ENABLE_BITVALC  BITVAL_7_C
#define RAMPS_E1_ENABLE_BITN     7


#define SET_BIT_OFF(v, bn)	v &= bn##_BITVALC
#define SET_BIT_ON(v, bn)	v |= bn##_BITVAL

#define PIN_X_STEP	RAMPS_X_STEP_PIN
#define PIN_X_STEP_PORT	RAMPS_X_STEP_PORT
#define PIN_X_STEP_BITVAL	RAMPS_X_STEP_BITVAL
#define PIN_X_STEP_BITVALC	RAMPS_X_STEP_BITVALC
#define SET_X_STEP_ON	SET_BIT_ON(PIN_X_STEP_PORT, PIN_X_STEP)
#define SET_X_STEP_OFF	SET_BIT_OFF(PIN_X_STEP_PORT, PIN_X_STEP)

#define PIN_X_DIR	RAMPS_X_DIR_PIN
#define PIN_X_DIR_PORT	RAMPS_X_DIR_PORT
#define PIN_X_DIR_BITVAL	RAMPS_X_DIR_BITVAL
#define PIN_X_DIR_BITVALC	RAMPS_X_DIR_BITVALC
#define SET_X_DIR_ON	SET_BIT_ON(PIN_X_DIR_PORT, PIN_X_DIR)
#define SET_X_DIR_OFF	SET_BIT_OFF(PIN_X_DIR_PORT, PIN_X_DIR)

#define PIN_X_ENA	RAMPS_X_ENABLE_PIN
#define PIN_X_ENA_PORT	RAMPS_X_ENABLE_PORT
#define PIN_X_ENA_BITVAL	RAMPS_X_ENABLE_BITVAL
#define PIN_X_ENA_BITVALC	RAMPS_X_ENABLE_BITVALC
#define SET_X_ENA_ON	SET_BIT_ON(PIN_X_ENA_PORT, PIN_X_ENA)
#define SET_X_ENA_OFF	SET_BIT_OFF(PIN_X_ENA_PORT, PIN_X_ENA)

#define PIN_Y_STEP	RAMPS_Y_STEP_PIN
#define PIN_Y_STEP_PORT	RAMPS_Y_STEP_PORT
#define PIN_Y_STEP_BITVAL	RAMPS_Y_STEP_BITVAL
#define PIN_Y_STEP_BITVALC	RAMPS_Y_STEP_BITVALC
#define SET_Y_STEP_ON	SET_BIT_ON(PIN_Y_STEP_PORT, PIN_Y_STEP)
#define SET_Y_STEP_OFF	SET_BIT_OFF(PIN_Y_STEP_PORT, PIN_Y_STEP)

#define PIN_Y_DIR	RAMPS_Y_DIR_PIN
#define PIN_Y_DIR_PORT	RAMPS_Y_DIR_PORT
#define PIN_Y_DIR_BITVAL	RAMPS_Y_DIR_BITVAL
#define PIN_Y_DIR_BITVALC	RAMPS_Y_DIR_BITVALC
#define SET_Y_DIR_ON	SET_BIT_ON(PIN_Y_DIR_PORT, PIN_Y_DIR)
#define SET_Y_DIR_OFF	SET_BIT_OFF(PIN_Y_DIR_PORT, PIN_Y_DIR)

#define PIN_Y_ENA	RAMPS_Y_ENABLE_PIN
#define PIN_Y_ENA_PORT	RAMPS_Y_ENABLE_PORT
#define PIN_Y_ENA_BITVAL	RAMPS_Y_ENABLE_BITVAL
#define PIN_Y_ENAC	RAMPS_Y_ENABLE_PINC
#define SET_Y_ENA_ON	SET_BIT_ON(PIN_Y_ENA_PORT, PIN_Y_ENA)
#define SET_Y_ENA_OFF	SET_BIT_OFF(PIN_Y_ENA_PORT, PIN_Y_ENA)

#define PIN_Z_STEP	RAMPS_Z_STEP_PIN
#define PIN_Z_STEP_PORT	RAMPS_Z_STEP_PORT
#define PIN_Z_STEP_BITVAL	RAMPS_Z_STEP_BITVAL
#define PIN_Z_STEP_BITVALC	RAMPS_Z_STEP_BITVALC
#define SET_Z_STEP_ON	SET_BIT_ON(PIN_Z_STEP_PORT, PIN_Z_STEP)
#define SET_Z_STEP_OFF	SET_BIT_OFF(PIN_Z_STEP_PORT, PIN_Z_STEP)

#define PIN_Z_DIR	RAMPS_Z_DIR_PIN
#define PIN_Z_DIR_PORT	RAMPS_Z_DIR_PORT
#define PIN_Z_DIR_BITVAL	RAMPS_Z_DIR_BITVAL
#define PIN_Z_DIRC	RAMPS_Z_DIR_PINC
#define SET_Z_DIR_ON	SET_BIT_ON(PIN_Z_DIR_PORT, PIN_Z_DIR)
#define SET_Z_DIR_OFF	SET_BIT_OFF(PIN_Z_DIR_PORT, PIN_Z_DIR)

#define PIN_Z_ENA	RAMPS_Z_ENABLE_PIN
#define PIN_Z_ENA_PORT	RAMPS_Z_ENABLE_PORT
#define PIN_Z_ENA_BITVAL	RAMPS_Z_ENABLE_BITVAL
#define PIN_Z_ENA_BITVALC	RAMPS_Z_ENABLE_BITVALC
#define SET_Z_ENA_ON	SET_BIT_ON(PIN_Z_ENA_PORT, PIN_Z_ENA)
#define SET_Z_ENA_OFF	SET_BIT_OFF(PIN_Z_ENA_PORT, PIN_Z_ENA)


#define PIN_X_ENDSTOP	RAMPS_X_MIN_PIN
#define PIN_Y_ENDSTOP	RAMPS_Y_MIN_PIN
#define PIN_Z_ENDSTOP	RAMPS_Z_MIN_PIN

/*
A9 		A10 	A11
PK1 	PK2 	PK3
PCINT17 PCINT18 PCINT19
*/
#define RAMPS_A9		63
#define RAMPS_A9_PORT	PORTK
#define RAMPS_A9_PINR	PINK
#define RAMPS_A9_BITN	1
#define RAMPS_A9_BITVAL	BITVAL_1

#define RAMPS_A10		64
#define RAMPS_A10_PORT	PORTK
#define RAMPS_A10_PINR	PINK
#define RAMPS_A10_BITN	2
#define RAMPS_A10_BITVAL	BITVAL_2

#define RAMPS_A11		65
#define RAMPS_A11_PORT	PORTK
#define RAMPS_A11_PINR	PINK
#define RAMPS_A11_BITN	3
#define RAMPS_A11_BITVAL	BITVAL_3

// Muve
#define PIN_ROTARY_A_CLK		RAMPS_A9
#define PIN_ROTARY_A_CLK_PORT	RAMPS_A9_PORT
#define PIN_ROTARY_A_CLK_PINR	RAMPS_A9_PINR
#define PIN_ROTARY_A_CLK_BITN	RAMPS_A9_BITN
#define READ_ROTARY_A_CLK		((RAMPS_A9_PINR & RAMPS_A9_BITVAL) ? 1 : 0)

// Gray
#define PIN_ROTARY_B_DT			RAMPS_A10
#define PIN_ROTARY_B_DT_PORT	RAMPS_A10_PORT
#define PIN_ROTARY_B_DT_PINR	RAMPS_A10_PINR
#define PIN_ROTARY_B_DT_BITN	RAMPS_A10_BITN
#define READ_ROTARY_B_DT		((RAMPS_A10_PINR & RAMPS_A10_BITVAL) ? 1 : 0)

// WHITE
#define PIN_ROTARY_SW			RAMPS_A11
#define PIN_ROTARY_SW_PORT		RAMPS_A11_PORT
#define PIN_ROTARY_SW_PINR		RAMPS_A11_PINR
#define PIN_ROTARY_SW_BITN		RAMPS_A11_BITN
#define READ_ROTARY_SW			((RAMPS_A11_PINR & RAMPS_A11_BITVAL) ? 1 : 0)


#endif

#endif
